import { Property, Testimonial } from "./types";

// Fotos de demo (Unsplash). En producción vienen de Cloudinary vía Strapi.
const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=70`;

export const PROPERTIES: Property[] = [
  {
    id: "1",
    slug: "casa-sant-quirze-del-valles-560000",
    title: "Casa a 4 vientos en Sant Quirze del Vallès",
    operation: "venta",
    type: "casa",
    status: "destacado",
    tag: "exclusiva",
    price: 560000,
    location: "Les Fonts",
    city: "Sant Quirze del Vallès",
    bedrooms: 4,
    bathrooms: 3,
    area: 180,
    reference: "SQ-1042",
    description:
      "Preciosa casa a 4 vientos en una de las mejores zonas de Sant Quirze del Vallès. Amplios espacios, jardín con piscina y excelentes acabados. Lista para entrar a vivir.",
    features: ["4 habitaciones", "3 baños", "Jardín con piscina", "Garaje 2 coches", "Parcela 450 m²"],
    equipment: ["Aire acondicionado", "Calefacción", "Cocina equipada", "Domótica", "Alarma"],
    energyCertificate: "C",
    lat: 41.5361,
    lng: 2.0822,
    images: [img("photo-1600596542815-ffad4c1539a9"), img("photo-1600585154340-be6161a56a0c"), img("photo-1600607687939-ce8a6c25118c"), img("photo-1600566753086-00f18fb6b3ea")],
    featured: true,
  },
  {
    id: "2",
    slug: "piso-sant-quirze-del-valles-450000",
    title: "Piso reformado con terraza",
    operation: "venta",
    type: "piso",
    status: "disponible",
    tag: "nuevo",
    price: 450000,
    location: "Centre",
    city: "Sant Quirze del Vallès",
    bedrooms: 4,
    bathrooms: 2,
    area: 140,
    reference: "SQ-1043",
    description:
      "Luminoso piso totalmente reformado en pleno centro, con terraza orientada al sur y plaza de parking incluida. A pocos minutos de la estación.",
    features: ["4 habitaciones", "2 baños", "Terraza 18 m²", "Parking incluido", "Ascensor"],
    equipment: ["Aire acondicionado", "Calefacción", "Armarios empotrados", "Cocina office"],
    energyCertificate: "B",
    lat: 41.5339,
    lng: 2.0813,
    images: [img("photo-1502672260266-1c1ef2d93688"), img("photo-1505691938895-1758d7feb511"), img("photo-1560448204-e02f11c3d0e2")],
    featured: true,
  },
  {
    id: "3",
    slug: "chalet-alquiler-sant-quirze-del-valles-1350",
    title: "Chalet en alquiler con jardín",
    operation: "alquiler",
    type: "chalet",
    status: "disponible",
    tag: "nuevo",
    price: 1350,
    location: "Can Pallàs",
    city: "Sant Quirze del Vallès",
    bedrooms: 3,
    bathrooms: 2,
    area: 110,
    reference: "SQ-1044",
    description:
      "Acogedor chalet en zona residencial tranquila, con jardín privado y mucha luz natural. Ideal para familias. Disponibilidad inmediata.",
    features: ["3 habitaciones", "2 baños", "Jardín privado", "Trastero", "Zona tranquila"],
    equipment: ["Calefacción", "Cocina equipada", "Armarios empotrados"],
    energyCertificate: "D",
    lat: 41.541,
    lng: 2.0765,
    images: [img("photo-1568605114967-8130f3a36994"), img("photo-1576941089067-2de3c901e126"), img("photo-1583608205776-bfd35f0d9f83")],
    featured: true,
  },
  {
    id: "4",
    slug: "casa-sant-quirze-del-valles-695000",
    title: "Casa de diseño con piscina",
    operation: "venta",
    type: "casa",
    status: "destacado",
    tag: "rebajado",
    price: 695000,
    location: "Sant Quirze Parc",
    city: "Sant Quirze del Vallès",
    bedrooms: 5,
    bathrooms: 3,
    area: 220,
    reference: "SQ-1045",
    description:
      "Espectacular casa de diseño con grandes ventanales, piscina y acabados de alta gama. Espacios diáfanos bañados de luz y un jardín de ensueño.",
    features: ["5 habitaciones", "3 baños", "Piscina", "Garaje 2 coches", "Parcela 600 m²"],
    equipment: ["Aerotermia", "Suelo radiante", "Cocina alta gama", "Domótica", "Placas solares"],
    energyCertificate: "A",
    lat: 41.5302,
    lng: 2.089,
    images: [img("photo-1613490493576-7fde63acd811"), img("photo-1564013799919-ab600027ffc6"), img("photo-1600210492486-724fe5c67fb0")],
    featured: true,
  },
  {
    id: "5",
    slug: "duplex-sant-quirze-del-valles-385000",
    title: "Dúplex con vistas despejadas",
    operation: "venta",
    type: "duplex",
    status: "disponible",
    price: 385000,
    location: "La Betzuca",
    city: "Sant Quirze del Vallès",
    bedrooms: 3,
    bathrooms: 2,
    area: 125,
    reference: "SQ-1046",
    description:
      "Dúplex moderno con vistas despejadas, gran salón comedor y terraza. Una opción perfecta para quienes buscan amplitud y luz.",
    features: ["3 habitaciones", "2 baños", "Terraza", "Trastero", "Ascensor"],
    equipment: ["Aire acondicionado", "Calefacción", "Cocina equipada"],
    energyCertificate: "C",
    lat: 41.5375,
    lng: 2.0798,
    images: [img("photo-1512917774080-9991f1c4c750"), img("photo-1493809842364-78817add7ffb"), img("photo-1493606278519-11aa9f86e40a")],
  },
  {
    id: "6",
    slug: "local-comercial-sant-quirze-del-valles-180000",
    title: "Local comercial a pie de calle",
    operation: "venta",
    type: "local",
    status: "disponible",
    price: 180000,
    location: "Centre",
    city: "Sant Quirze del Vallès",
    bedrooms: 0,
    bathrooms: 1,
    area: 95,
    reference: "SQ-1047",
    description:
      "Local comercial diáfano a pie de calle en zona de mucho paso. Excelente oportunidad de inversión o para tu negocio.",
    features: ["95 m²", "Escaparate", "Aseo", "Zona comercial", "Mucho paso"],
    equipment: ["Persiana automática", "Instalación eléctrica nueva"],
    energyCertificate: "en trámite",
    lat: 41.5331,
    lng: 2.0825,
    images: [img("photo-1441986300917-64674bd600d8"), img("photo-1604719312566-8912e9227c6a")],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  { name: "Laura G.", rating: 5, text: "Un trato excelente y muy profesional. Nos ayudaron en todo el proceso de compra y fueron muy cercanos." },
  { name: "Xavier M.", rating: 5, text: "Vendimos nuestra casa en tiempo récord y al mejor precio. Sin duda, los recomendaría." },
  { name: "Marta P.", rating: 5, text: "Gran equipo y grandes profesionales. Nos asesoraron en todo momento, con total transparencia." },
  { name: "Jordi R.", rating: 5, text: "Conocen el mercado de Sant Quirze como nadie. Encontramos nuestro piso ideal en dos semanas." },
];
